Taking code snapshot... done
Sending code snapshot to Mortar... done
2014-11-20 18:42:17,034 [28088:MainThread] (worker.py:275)  DEBUG - Checking if ProcessDay(environment=dev, data_date=2014-11-19) is complete
2014-11-20 18:42:17,166 [28088:MainThread] (worker.py:327)  INFO  - Scheduled ProcessDay(environment=dev, data_date=2014-11-19) (PENDING)
2014-11-20 18:42:17,166 [28088:MainThread] (worker.py:275)  DEBUG - Checking if Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/test.json, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0) is complete
2014-11-20 18:42:17,337 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/output/2014-11-19/test.json does not exist
2014-11-20 18:42:17,339 [28088:MainThread] (worker.py:327)  INFO  - Scheduled Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/test.json, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0) (PENDING)
2014-11-20 18:42:17,340 [28088:MainThread] (worker.py:275)  DEBUG - Checking if TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19) is complete
2014-11-20 18:42:17,545 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/work/2014-11-19/test.json does not exist
2014-11-20 18:42:17,547 [28088:MainThread] (worker.py:327)  INFO  - Scheduled TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19) (PENDING)
2014-11-20 18:42:17,547 [28088:MainThread] (worker.py:275)  DEBUG - Checking if FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/test.metadata) is complete
2014-11-20 18:42:17,702 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/input/2014-11-19/test.metadata does not exist
2014-11-20 18:42:17,703 [28088:MainThread] (worker.py:306)  WARNI - Task FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/test.metadata) is not complete and run() is not implemented. Probably a missing external dependency.
2014-11-20 18:42:17,704 [28088:MainThread] (worker.py:327)  INFO  - Scheduled FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/test.metadata) (PENDING)
2014-11-20 18:42:17,704 [28088:MainThread] (worker.py:275)  DEBUG - Checking if FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json) is complete
2014-11-20 18:42:17,918 [28088:MainThread] (worker.py:327)  INFO  - Scheduled FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/test.json) (DONE)
2014-11-20 18:42:17,919 [28088:MainThread] (worker.py:275)  DEBUG - Checking if Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0) is complete
2014-11-20 18:42:18,077 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk does not exist
2014-11-20 18:42:18,079 [28088:MainThread] (worker.py:327)  INFO  - Scheduled Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0) (PENDING)
2014-11-20 18:42:18,079 [28088:MainThread] (worker.py:275)  DEBUG - Checking if TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19) is complete
2014-11-20 18:42:18,241 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/work/2014-11-19/sw33-t3vk does not exist
2014-11-20 18:42:18,243 [28088:MainThread] (worker.py:327)  INFO  - Scheduled TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19) (PENDING)
2014-11-20 18:42:18,243 [28088:MainThread] (worker.py:275)  DEBUG - Checking if FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk.metadata) is complete
2014-11-20 18:42:18,327 [28088:MainThread] (worker.py:327)  INFO  - Scheduled FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk.metadata) (DONE)
2014-11-20 18:42:18,327 [28088:MainThread] (worker.py:275)  DEBUG - Checking if FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk) is complete
2014-11-20 18:42:18,411 [28088:MainThread] (worker.py:327)  INFO  - Scheduled FileExists(path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk) (DONE)
2014-11-20 18:42:18,411 [28088:MainThread] (interface.py:193)  INFO  - Done scheduling tasks
2014-11-20 18:42:18,412 [28088:MainThread] (worker.py:436)  INFO  - Running Worker with 1 processes
2014-11-20 18:42:18,412 [28088:MainThread] (worker.py:355)  DEBUG - Asking scheduler for work...
2014-11-20 18:42:18,412 [28088:MainThread] (worker.py:463)  DEBUG - Pending tasks: 5
2014-11-20 18:42:18,412 [28088:MainThread] (worker.py:59)  INFO  - [pid 28088] Worker Worker(salt=119932015, host=192-168-140-129.vpn.shanghai.nyu.edu, username=drp354, pid=28088) running   TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19)
2014-11-20 18:42:18,880 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 0 in sw33-t3vk transformed to common format
2014-11-20 18:42:18,883 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 10 in sw33-t3vk transformed to common format
2014-11-20 18:42:18,903 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 100 in sw33-t3vk transformed to common format
2014-11-20 18:42:19,015 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 1000 in sw33-t3vk transformed to common format
2014-11-20 18:42:19,996 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 10000 in sw33-t3vk transformed to common format
2014-11-20 18:42:21,067 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 20000 in sw33-t3vk transformed to common format
2014-11-20 18:42:22,142 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 30000 in sw33-t3vk transformed to common format
2014-11-20 18:42:23,223 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 40000 in sw33-t3vk transformed to common format
2014-11-20 18:42:24,297 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 50000 in sw33-t3vk transformed to common format
2014-11-20 18:42:25,373 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 60000 in sw33-t3vk transformed to common format
2014-11-20 18:42:26,450 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 70000 in sw33-t3vk transformed to common format
2014-11-20 18:42:27,532 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 80000 in sw33-t3vk transformed to common format
2014-11-20 18:42:28,614 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 90000 in sw33-t3vk transformed to common format
2014-11-20 18:42:29,681 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 100000 in sw33-t3vk transformed to common format
2014-11-20 18:42:30,740 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 110000 in sw33-t3vk transformed to common format
2014-11-20 18:42:31,797 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 120000 in sw33-t3vk transformed to common format
2014-11-20 18:42:32,861 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 130000 in sw33-t3vk transformed to common format
2014-11-20 18:42:33,932 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 140000 in sw33-t3vk transformed to common format
2014-11-20 18:42:35,001 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 150000 in sw33-t3vk transformed to common format
2014-11-20 18:42:36,072 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 160000 in sw33-t3vk transformed to common format
2014-11-20 18:42:37,137 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 170000 in sw33-t3vk transformed to common format
2014-11-20 18:42:38,204 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 180000 in sw33-t3vk transformed to common format
2014-11-20 18:42:39,267 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 190000 in sw33-t3vk transformed to common format
2014-11-20 18:42:40,328 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 200000 in sw33-t3vk transformed to common format
2014-11-20 18:42:41,391 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 210000 in sw33-t3vk transformed to common format
2014-11-20 18:42:42,465 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 220000 in sw33-t3vk transformed to common format
2014-11-20 18:42:43,535 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 230000 in sw33-t3vk transformed to common format
2014-11-20 18:42:44,603 [28088:MainThread] (cusp_dataset_etl.py:173)  INFO  - Line 240000 in sw33-t3vk transformed to common format
2014-11-20 18:42:49,561 [28088:MainThread] (worker.py:81)  INFO  - [pid 28088] Worker Worker(salt=119932015, host=192-168-140-129.vpn.shanghai.nyu.edu, username=drp354, pid=28088) done      TransformInputData(input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19)
2014-11-20 18:42:49,562 [28088:MainThread] (worker.py:445)  DEBUG - 1 running tasks, waiting for next task to finish
2014-11-20 18:42:49,563 [28088:MainThread] (worker.py:355)  DEBUG - Asking scheduler for work...
2014-11-20 18:42:49,563 [28088:MainThread] (worker.py:463)  DEBUG - Pending tasks: 4
2014-11-20 18:42:49,564 [28088:MainThread] (worker.py:59)  INFO  - [pid 28088] Worker Worker(salt=119932015, host=192-168-140-129.vpn.shanghai.nyu.edu, username=drp354, pid=28088) running   Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0)
2014-11-20 18:42:49,886 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/work/2014-11-19/Geocode-Running does not exist
2014-11-20 18:42:50,208 [28088:MainThread] (mortartask.py:328)  INFO  - Submitted new job to mortar with job_id [546e7d0e5383c228a49e63ae]
2014-11-20 18:42:50,520 [28088:MainThread] (mortartask.py:356)  INFO  - Mortar job_id [546e7d0e5383c228a49e63ae] switched to status_code [validating_script], description: Validating Script
2014-11-20 18:43:05,876 [28088:MainThread] (mortartask.py:356)  INFO  - Mortar job_id [546e7d0e5383c228a49e63ae] switched to status_code [execution_error], description: Execution Error
2014-11-20 18:43:06,012 [28088:MainThread] (s3.py:113)  DEBUG - Deleting work/2014-11-19/Geocode-Running from bucket cusp-dataset-search-dev
2014-11-20 18:43:06,013 [28088:MainThread] (mortartask.py:274)  INFO  - Mortar script failed: removing incomplete data in <luigi.s3.S3Target object at 0x7fddc7f16a10>
2014-11-20 18:43:06,164 [28088:MainThread] (s3.py:89)  DEBUG - Path s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk does not exist
2014-11-20 18:43:06,164 [28088:MainThread] (s3.py:97)  DEBUG - Could not delete s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk; path does not exist
2014-11-20 18:43:06,165 [28088:MainThread] (worker.py:89)  ERROR - [pid 28088] Worker Worker(salt=119932015, host=192-168-140-129.vpn.shanghai.nyu.edu, username=drp354, pid=28088) failed    Geocode(run_on_single_use_cluster=False, use_spot_instances=True, git_ref=not-set-flag, notify_on_job_finish=False, job_polling_interval=5, num_polling_retries=3, pig_version=0.12, input_data_path=s3://cusp-dataset-search-dev/input/2014-11-19/sw33-t3vk, work_data_path=s3://cusp-dataset-search-dev/work/2014-11-19, output_data_path=s3://cusp-dataset-search-dev/output/2014-11-19/sw33-t3vk, geojson_s3_bucket=cusp-dataset-search-dev, geojson_s3_key=input/geo/ny_zipcodes.json, cluster_size=0)
Traceback (most recent call last):
  File "/home/drp354/GRA/mortartest-13-nov/cusp-dataset-search/.mortar-local/pythonenv/lib/python2.7/site-packages/luigi/worker.py", line 77, in run
    self.task.run()
  File "/home/drp354/GRA/mortartest-13-nov/cusp-dataset-search/.mortar-local/pythonenv/lib/python2.7/site-packages/mortar/luigi/mortartask.py", line 276, in run
    raise Exception('Mortar job_id [%s] failed with status_code: [%s], error details: %s' % (job_id, final_job_status_code, job.get('error')))
Exception: Mortar job_id [546e7d0e5383c228a49e63ae] failed with status_code: [execution_error], error details: {u'line_number': None, u'message': u'File \u2018../udfs/python/geocode.py\u2019 does not exist.', u'column_number': None, u'type': u'RuntimeError', u'stack_trace': u'java.io.FileNotFoundException: File \u2018../udfs/python/geocode.py\u2019 does not exist.\n\tat org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:407)\n\tat org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:251)\n\tat org.apache.pig.impl.io.FileLocalizer.fetchFilesInternal(FileLocalizer.java:748)\n\tat org.apache.pig.impl.io.FileLocalizer.fetchFile(FileLocalizer.java:692)\n\tat org.apache.pig.PigServer.registerCode(PigServer.java:592)\n\tat org.apache.pig.tools.grunt.GruntParser.processRegister(GruntParser.java:490)\n\tat org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:556)\n\tat org.apache.pig.tools.grunt.GruntParser.loadScript(GruntParser.java:578)\n\tat org.apache.pig.tools.grunt.GruntParser.processExplain(GruntParser.java:374)\n\tat org.apache.pig.tools.grunt.GruntParser.processExplain(GruntParser.java:348)\n\tat org.apache.pig.tools.pigscript.parser.PigScriptParser.Explain(PigScriptParser.java:1011)\n\tat org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:434)\n\tat org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:199)\n\tat org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:174)\n\tat org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)\n\tat org.apache.pig.Main.run(Main.java:512)\n\tat org.apache.pig.PigRunner.run(PigRunner.java:49)\n\tat com.mortardata.hawk.HawkMain.runHawkPig(HawkMain.java:26)\n\tat com.mortardata.hawk.HawkMain.main(HawkMain.java:93)\n'}
2014-11-20 18:43:06,166 [28088:MainThread] (notifications.py:122)  INFO  - Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
2014-11-20 18:43:06,167 [28088:MainThread] (worker.py:445)  DEBUG - 1 running tasks, waiting for next task to finish
2014-11-20 18:43:06,169 [28088:MainThread] (worker.py:355)  DEBUG - Asking scheduler for work...
2014-11-20 18:43:06,169 [28088:MainThread] (worker.py:346)  INFO  - Done
2014-11-20 18:43:06,169 [28088:MainThread] (worker.py:347)  INFO  - There are no more tasks to run at this time
2014-11-20 18:43:06,169 [28088:MainThread] (worker.py:352)  INFO  - There are 3 pending tasks possibly being run by other workers
2014-11-20 18:43:06,212 [28088:Thread-1] (worker.py:164)  INFO  - Worker Worker(salt=119932015, host=192-168-140-129.vpn.shanghai.nyu.edu, username=drp354, pid=28088) was stopped. Shutting down Keep-Alive thread

